name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: ok-nick/setup-aftman@v0.4.2
      name: install Aftman
      with:
          version: "^0.2.7"
          token: ${{ SECRET.GITHUB_TOKEN }}
      
    - name: Lint
      run: |
        selene ./modules

  style:
    name: Styling
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: JohnnyMorganz/StyLua@0.20.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --check .