name: Deploy to Staging

on:
  push:
    branches:
    - main

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: ok-nick/setup-aftman@v0.4.2
      name: Install aftman
      with:
          token: ${{ SECRETS.GITHUB_TOKEN }}

    - run: rojo build -o moonzr-towerDefense.rbxl

    - run: rbxcloud experience publish --filename moonzr-towerDefense.rbxl --place-id 16653174260 --universe-id 5728027313 --version-type published --api-key ${{ secrets.API_KEY }}
# test